colleage/account/urls.py
from django.urls import path, include
from . import views


app_name = 'account'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

colleage/config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.views import dashboard


admin.site.site_header = "SMS-LIO Admin"
admin.site.site_title = "SMS-LIO Admin Portal"
admin.site.index_title = "Welcome to SMS-LIO Portal"

urlpatterns = [
    path('__debug__', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', dashboard, name='index_view'),
    path('account/', include('account.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    # path('misc/', include('admin_tools.urls')),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
    name='password_reset_complete'
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

colleage/students/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls import url
app_name = 'students'

urlpatterns = [
    path('all/', views.students_view, name='all_student'),
    path('add/', views.add_student_view, name='add_student'),
    path('update/<int:pk>/', views.student_update_view.as_view(),
         name='update_student'),
    path('<int:pk>/detail/', views.student_detail_view.as_view(),
         name='student_details'),
    path('<int:pk>/delete/', views.student_delete_view, name='delete_student'),
    re_path('^csv/$', views.export_users_csv_view, name='export_users_details_csv'),
]

colleage/teachers/urls.py
from django.urls import path
from . import views


app_name = 'teachers'

urlpatterns = [
    path('all/', views.teachers_view, name='all_teacher'),

]

colleage/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% load permission_tags %}
<head>
  <meta charset="UTF-8">
  <title>School DASHBOARD</title>
  <!-- FONT AWESOME KIT -->
  <script src="https://kit.fontawesome.com/16475baae0.js" crossorigin="anonymous"></script>
  <!-- GOOGLE FONT -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
  <!-- BOOTSTRAP4 CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- CUSTOM CSS -->
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

</head>

<body class="bg-light">

  <section id="dashboard">
    <div class="container-fluid">
      <div class="dashboard-container row">
        <!-- START SIDENAV -->
        <div class="col-12 col-sm-12 col-md-4 col-lg-2 sidenav">
          <div class="logo">
            <!-- <img src="{% static 'images/logo.png' %}" alt="">-->
            <h4>SCHOOl ADMIN  {{user.get_username}}</h4>
          </div>
          <div class="sn-group">
            <a href="{% url 'account:dashboard' %}" class="sn-link dash-home">
              <i class="fas fa-tachometer-alt"></i>Dashboard
            </a>
            <a class="sn-link dash-home" href="{% url 'index_view' %}" target="_blank">
              <i class="fas fa-globe-asia"></i>Visit Site
            </a>
          </div>

          {% if user|has_role:'admin,student' %}
            <div class="sn-group">
              <h5>student</h5>
              <nav>
                {% if user|has_role:'admin' %}
                <a class="sn-link" href="{% url 'students:add_student' %}">
                  <i class="fas fa-user-plus"></i>admission
                </a>
                {% endif %}
                <a href="{% url 'students:all_student' %}" class="sn-link">
                  <i class="fas fa-th-list"></i>all student
                </a>

              </nav>
            </div>
          {% endif %}

          {% if user|has_role:'admin,teacher,student'  %}
            <div class="sn-group">
              <h5>teacher</h5>
              <nav>
                {% if user|has_role:'admin'  %}
                  <a class="sn-link" href="">
                    <i class="fas fa-user-tie"></i>new teacher
                  </a>
                  <a href="" class="sn-link">
                    <i class="fas fa-id-card-alt"></i>promotion</a>
                {% endif %}
                <a href="{% url 'teachers:all_teacher' %}" class="sn-link">
                  <i class="fas fa-th-list"></i>teachers
                </a>

              </nav>
            </div>
          {% endif %}

        </div>
        <!-- END OF SIDENAV -->

        <!-- START DASHBOARD BODY -->
        <div class="col-12 col-sm-12 col-md-8 col-lg-10 px-0 dashbody">
          <!-- NAVIGATION TOP -->
          <nav class="navbar navbar-expand-lg navbar-light bg-light shadow py-3 px-5">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
              aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <form id="searchForm" class="form-inline">
                <input class="form-control" type="search" placeholder="Search for..." aria-label="Search">
                <button id="searchBtn" class="btn lio-primary-bg my-2 my-sm-0" type="submit"><i
                    class="fas fa-search"></i></button>
              </form>
              <div class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false"><i class="fas fa-user-circle fa-lg"></i></a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">
                      Logout {{ user.username }}
                    </a>
                  </div>
                </li>
              </div>
            </div>
          </nav>
          <!-- END NAV TOP -->

          <div id="dash-body-inner" class="container-fluid p-5">

            {% block dashboard-body %}

            <!-- topstat row -->
            <div class="row m-0 p-0">
              <h3 class="mb-3">Dashboard</h3>
              <div class="col-12 p-0">
                <div class="topstat d-flex justify-content-between">
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>students</p>
                      <h3>{{ total_students }}</h3>
                    </div>
                  </div>
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>teachers</p>
                      <h3>{{ total_teachers }}</h3>
                    </div>
                  </div>
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>clubs</p>
                      <h3>20</h3>
                    </div>
                  </div>
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>books</p>
                      <h3>2000</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- second row -->
            <div id="second-row" class="row m-0 p-0">
              <div class="col-12 mt-5 p-0 d-flex justify-content-between">
                <div class="card">
                  <div class="card-header">
                    <h5>upcoming events</h5>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between">
                      <span class="name">Seminar on Machine Learning</span>
                      <span class="date">december 12</span>
                      <span class="organizer">dpi decoder</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                      <span class="name">Spelling Bee</span>
                      <span class="date">november 26</span>
                      <span class="organizer">english club</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                      <span class="name">hello! you.</span>
                      <span class="date">december 2</span>
                      <span class="organizer">cultural club</span>
                    </li>
                  </ul>
                </div>
                <div class="card">
                  <div class="card-header">
                    <h5>Notice Board</h5>
                  </div>
                  <ul class="list-group">
                    <li class="list-group-item">
                      <h5 class="date">23 nov 2019</h5>
                      <h5>Admit card collecting notice.</h5>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- end of second row -->

            <!-- payment row -->
            <div class="row m-0 p-0">
              <h3 class="mt-5 mb-3">Stuff Payment</h3>
              <div class="col-12 p-0 d-flex justify-content-between">
                <div class="unpaid card">
                  <ul class="list-group list-group-flush">
                    <li class="title list-group-item">
                      <h5>unpaid</h5>
                    </li>
                    <li class="list-group-item">
                      <input type="checkbox" name="paid"> Md. Shariful Islam
                    </li>
                    <li class="list-group-item">
                      <input type="checkbox" name="paid"> Md. Shariful Islam
                    </li>
                    <li class="list-group-item">
                      <input type="checkbox" name="paid"> Md. Shariful Islam
                    </li>
                  </ul>
                </div>
                <div class="paid card">
                  <ul class="list-group list-group-flush">
                    <li class="title list-group-item">
                      <h5>paid</h5>
                    </li>
                    <li class="list-group-item">Suma rani das</li>
                    <li class="list-group-item">Johir chy</li>
                  </ul>
                </div>
              </div>
            </div>

            {% endblock dashboard-body %}

          </div>
          <!-- <footer id="footer">
            <div class="container">
              <div class="row">
                <div class="col-12 py-1">
                  <p>&copy;copyright 2020, reserved by <em>pidevs</em></p>
                </div>
              </div>
            </div>
          </footer> -->
        </div>
        <!-- END DASHBOARD BODY -->
      </div> <!-- dashboard container fluid -->

    </div>
  </section>


  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
</body>

</html>

colleage/templates/index.html
{% extends 'layout.html' %}

{% block content%}
<!-- Home Hero Section -->
<section id="home-hero">
  <div id="home-hero--inner">
    <div class="container">
      <div class="row py-5 justify-content-center align-items-center">
        <div class="col-12 py-5 text-center">
          <h1>Daffodil Polytechnic Institute</h1>
          <h5><em>Boost your knowledge and gain career</em></h5>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

colleage/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %} {% endblock %}
  </title>
  <!-- FONT AWESOME KIT -->
  <script src="https://kit.fontawesome.com/16475baae0.js" crossorigin="anonymous"></script>
  <!-- GOOGLE FONT -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>


  <!-- SITE BODY -->
  {% block content %}
  {% endblock %}
  <!--SITE BODT END-->


  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
</body>

</html>