colleage/config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.views import dashboard


admin.site.site_header = "SMS-LIO Admin"
admin.site.site_title = "SMS-LIO Admin Portal"
admin.site.index_title = "Welcome to SMS-LIO Portal"

urlpatterns = [
    path('__debug__', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', dashboard, name='index_view'),
    path('account/', include('account.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    # path('misc/', include('admin_tools.urls')),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
    name='password_reset_complete'
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

colleage/students/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls import url
app_name = 'students'

urlpatterns = [
    path('all/', views.students_view, name='all_student'),
    path('add/', views.add_student_view, name='add_student'),
    path('update/<int:pk>/', views.student_update_view.as_view(),
         name='update_student'),
    path('<int:pk>/detail/', views.student_detail_view.as_view(),
         name='student_details'),
    path('<int:pk>/delete/', views.student_delete_view, name='delete_student'),
    re_path('^csv/$', views.export_users_csv_view, name='export_users_details_csv'),
]

colleage/students/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    photo = models.ImageField(upload_to='students',
                              default='studentavar.png')
    date_of_birth = models.DateField(blank=True, null=True)
    registration_number = models.CharField(max_length=6, unique=True)
    mobile = models.CharField(max_length=11, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount = models.FloatField(null=True, blank=True, default=None)
    paid_amount = models.FloatField(null=True, blank=True, default=None)
    due_amount = models.FloatField(null=True, blank=True, default=None)
    add_amount = models.FloatField(null=True, blank=True, default=None)
    # def __str__(self):
    #     return '{} ({}) semester {} dept.'.format(
    #         self.name
    #     )

    class Meta:
        ordering = ['registration_number']

colleage/students/forms.py
from .models import Student
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import Tab, TabHolder
from crispy_forms.layout import (Layout, Fieldset, Field,
                                 ButtonHolder, Submit, Div)

from django.contrib.auth.models import User
from .models import Student
import django_filters

class StudentForm(forms.ModelForm):
    username = forms.CharField(label='User Name',
                               widget=forms.TextInput)
    first_name = forms.CharField(label='First Name',
                                widget=forms.TextInput)
    email = forms.CharField(label='Email',
                                 widget=forms.TextInput)
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password1 = forms.CharField(label='Password1',
                                 widget=forms.PasswordInput)

    class Meta:
        model = Student
        fields = [
            'photo',
            'date_of_birth',
            'registration_number',
            'mobile',
            'total_amount','paid_amount','due_amount','add_amount',
            'username', 'first_name', 'email', 'password', 'password1'
        ]

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            TabHolder(
                Tab('Student Personal Info',
                    'username',
                    'first_name',
                    'email',
                    'password',
                    'password1',
                    css_class="extra"),
                Tab('Student Register Info',
                    'photo',
                    'date_of_birth',
                    'registration_number',
                    'mobile',
                    ),
                Tab('Student Payment Info',
                    Field('total_amount',
                          'paid_amount',
                          'due_amount',
                          ButtonHolder(
                              Submit('submit', 'Admit Student',
                                     css_class='float-right btn-dark mr-3')
                          ),
                          css_class="extra"),
                    ),
            ),
        )

    def save(self):

        user = User.objects.create_user(username=self.cleaned_data['username'],
                                        password=self.cleaned_data['password'])
        user.first_name = self.cleaned_data['first_name']
        user.email = self.cleaned_data['email']
        user.save()
        student_profile = Student.objects.create(user=user, photo=self.cleaned_data['photo'],
                                                        date_of_birth=self.cleaned_data['date_of_birth'],
                                                        mobile=self.cleaned_data['mobile'],
                                                        registration_number=self.cleaned_data['registration_number'],
                                                        total_amount=self.cleaned_data['total_amount'],
                                                        paid_amount=self.cleaned_data['paid_amount'],
                                                        due_amount=self.cleaned_data['due_amount'])
        return user, student_profile

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password didn\'t match!')
        return cd['password2']

colleage/students/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Student
from .forms import StudentForm
import csv
from send_mail.email import send_email
from django.http import HttpResponse
from django.contrib.auth.models import User
from rolepermissions.roles import assign_role
from django.template.loader import render_to_string
from django.utils.html import strip_tags

@login_required
def add_student_view(request):
    """
    :param request:
    :return: admission form to
    logged in user.
    """
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            user, student = form.save()
            assign_role(user, 'student')
            # :send mail section

            # html_message = render_to_string('students/email.html',
            #                                 {'username': form.cleaned_data.get("username"),
            #                                  'password': form.cleaned_data.get("password")})
            # plain_message = strip_tags(html_message)
            # send_email("Student Credentials", plain_message, (user.email,))
            pk = form.instance.pk
            return render(request, 'students/student_sucess.html')
    else:
        form = StudentForm()
    context = {'form': form}
    return render(request, 'students/addstudent.html', context)

@login_required
def students_view(request):
    """
    :param request:
    :return: renders student list with all department
    and semesters list.
    """
    all_students = Student.objects.all()
    context = {'students': all_students}
    return render(request, 'students/students_list.html', context)

class student_detail_view(LoginRequiredMixin, DetailView):
    model = Student
    template_name = 'students/student_details.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        obj = kwargs['object']
        pk = obj.id
        student = Student.objects.get(pk=pk)
        # get student object
        # for showing subjects in option form
        # student_subject_qs = student.has_subjects()[0]
        # student_subject_qs = student_subject_qs.subjects.all()
        # context['subjects'] = student_subject_qs
        # getting result objects
        # semesters = range(1, student.semester.number + 1)
        context['student'] = student
        return context

class student_update_view(LoginRequiredMixin, UpdateView):
    """
    renders a student update form to update students details.
    """
    model = Student
    fields = ['photo','mobile', 'total_amount', 'paid_amount', 'due_amount']
    template_name = 'students/update_student.html'

    def get_success_url(self):
        student_id = self.kwargs['pk']
        return reverse_lazy('students:student_details', kwargs={'pk': student_id})




@login_required
def student_delete_view(request, pk):
    student = Student.objects.get(pk=pk)
    student.delete()
    return redirect('students:all_student')



def export_users_csv_view(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="students.csv"'

    writer = csv.writer(response)
    writer.writerow(['Username', 'First name', 'Email address','Mobile', 'Total Fee','Paid amount','Due amount'])

    students = Student.objects.all()
    # users = User.objects.all().values_list('username', 'first_name', 'email')
    for student in students:
        user_data = [student.user.username, student.user.first_name, student.user.email,
                     student.mobile, student.total_amount, student.paid_amount, student.due_amount]
        writer.writerow(user_data)

    return response

colleage/templates/students/addstudent.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<form action="." method="post" class="admission-form d-block">
  <div class="alert alert-warning">
    <p>Fill up all the required field first, then click <em>Admit Student</em></p>
  </div>
  {% csrf_token %}
  {% crispy form %}
  <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

colleage/templates/students/email.html
<html>
<center>You have successfully registered in School student.</center>
<br/>
<center>Please find the user name and password to login to the account</center>
<br/>
<center>Username:{{username}}</center>
<br/>
<center>Password :{{password}}</center>
</html>>

colleage/templates/students/result.html
{% extends 'layout.html' %}
{% load student_tags %}
{% load static %}


{% block content %}
<div class="container">
  <div id="result_row" class="row mt-5 justify-content-between">
    <!-- SEARCH COLUMN -->
    <div class="col-12">
      <form class="form-inline">
        <div class="form-group mx-sm-3 mb-2">
          <label for="studentId" class="sr-only">Student ID</label>
          <input name="student_id" type="text" class="form-control">
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <label for="semester" class="sr-only">Semester</label>
          <input name="semester" type="text" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Search</button>
      </form>
    </div>
    <!-- RESULT TABLE COLUMN -->
    {% if student %}
    <div class="col-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td colspan="2">Larry the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}

colleage/templates/students/result_in_detail.html
{% extends 'layout.html' %}
{% load static %}
{% load student_tags %}

{% block content %}
<section id="student-detail-section header">
    <div id="student-detail-section--inner">
        <div class="container">
            <a href="{% url 'index_view' %}" class="btn btn-danger">
                Dashboard
            </a>
            <a href="{% url 'students:delete_student' pk=student.pk %}" class="btn btn-danger">
                <i class="fas fa-trash-alt"></i>
            </a>
            <a href="{% url 'students:update_student' pk=student.id %}" class="btn btn-secondary">
                <i class="fas fa-edit"></i>
            </a>
            <div class="row py-5">
                <div class="col-3">
                    <img class="student-profile-img" src="{{ student.photo.url }}" alt="" width="200" height="200">
                </div>
                <div class="col-8">
                    <h2>{{ student.name }}</h2>
                    <h4>{{ student.department }} {{ student.semester }}</h4>
                    <h4>Session: {{ student.ac_session }}</h4>
                    {% if student.mobile %}
                    <h4>Mobile: {{ student.mobile }}</h4>
                    {% endif %}
                    {% if student.email %}
                    <h4>Mail: {{ student.email }}</h4>
                    {% endif %}
                    {% if student.guardian_mobile %}
                    <h4>Guardian: {{ student.guardian_mobile }}</h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mt-5" id="student-information">
    <div class="container">
        <div class="row">
            <div class="col-8">
                <h3>Result(s):</h3>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Subject</th>
                            <th scope="col">Marks</th>
                            <th scope="col">GPA</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for result in results %}
                        <tr>
                            <td>{{ result.subject }}</td>
                            <td>{{ result.marks }}</td>
                            <td>{{ result.grade }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div> <!-- end of row -->
    </div>
</section>
{% endblock %}

colleage/templates/students/student_details.html
{% extends 'layout.html' %}
{% load static %}
{% load permission_tags %}
{% block content %}
<section id="student-detail-section header">
  <div id="student-detail-section--inner">
    <div class="container">
      <a href="{% url 'index_view' %}" class="btn btn-danger">
        Dashboard
      </a>
      {% if user|has_role:'admin'%}
        <a href="{% url 'students:delete_student' pk=student.pk %}" class="btn btn-danger">
          <i class="fas fa-trash-alt"></i>
        </a>
        <a href="{% url 'students:update_student' pk=student.id %}" class="btn btn-secondary">
          <i class="fas fa-edit"></i>
        </a>
      {% endif %}
      <div class="row py-5">
        <div class="col-3">
          <img class="student-profile-img" src="{{ student.photo.url }}" alt="" width="200" height="200">
        </div>
        <div class="col-8">
          <h4>Name:- {{ student.user.username }}</h4>
          <h4>Department:- Computers &nbsp; 2nd</h4>
          <h4>Std No: {{ student.registration_number }}</h4>
          {% if student.mobile %}
            <h4>Mobile: {{ student.mobile }}</h4>
          {% endif %}
          {% if student.user.email %}
          <h4>Mail: {{ student.user.email }}</h4>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
</section>

<section class="mt-5" id="student-information">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <h3>Result(s):</h3>

        <!-- Result Form Modal -->
        <div class="modal fade" id="resultForm" tabindex="-1">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Result For:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form  method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="marks">Marks</label>
                    <input type="number" class="form-control" name="marks" id="marks">
                  </div>
                  <div class="form-group">
                    <label for="subject">Subject</label>
                    <select class="form-control" id="subject" name="subject">
                      <input type="text" class="form-control" name="marks" id="subjects">
                    </select>
                  </div>
                  <input type="submit" value="Save">
                </form>
              </div>
            </div>
          </div>
        </div>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">
                <button type="button" class="btn btn-sm btn-success btn-block" data-toggle="modal" data-target="#resultForm">
                  <i class="fas fa-plus"></i> Add New Record
                </button>
              </th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td>
                  <a>Semister1</a>
                </td>
                <td>
                  <a>Semister2</a>
                </td>
              </tr>
          </tbody>
        </table>
      </div>
      <div class="col-4">
        <h3>Attendance:</h3>
        <a href="" class="btn btn-sm btn-success">
          <i class="fas fa-plus"></i> Add New Record
        </a>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Semester</th>
              <th scope="col">Avg.</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-4">
        <h3>Academic Report(s):</h3>
        <a href="" class="btn btn-sm btn-success">
          <i class="fas fa-plus"></i> Add New Record
        </a>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Semester</th>
              <th scope="col">Refference</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Mark</td>
              <td>Otto</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div> <!-- end of row -->
  </div>
</section>
{% endblock %}

colleage/templates/students/student_list_sidebar.html
<ul class="list-group filterbox">
    <li class="active list-group-item">
        <p>filter by</p>
    </li>
    {% if departments %}
    <li class="list-group-item">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseDept" aria-expanded="true"
            aria-controls="collapseDept">
            Department
        </button>
        <div id="accordion">
            <ul class="list-group-flush collapse show" id="collapseDept" data-parent="#accordion">
                {% for dept in departments %}
                <li class="list-group-item">
                    <a href="{% url 'students:students_by_dept' pk=dept.id %}">{{ dept|truncatewords:3 }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </li>
    {% endif %}
    <li class=" list-group-item">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseSemester" aria-expanded="true"
            aria-controls="collapseSemester">
            Semester
        </button>
        <div id="accordion">
            <ul class="list-group-flush collapse" id="collapseSemester" data-parent="#accordion">
                {% for sem in semesters %}
                <li class="list-group-item">
                    <a href="">{{ sem }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </li>
    <li class="list-group-item">
        <a href="">all</a>
    </li>
</ul>

colleage/templates/students/student_payment.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<form action="." method="post" class="admission-form d-block">
  <div class="alert alert-warning">
    <p>Fill up all the required field first, then click <em>Student Payment</em></p>
  </div>
  {% csrf_token %}
  {% crispy form %}
  <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

colleage/templates/students/student_sucess.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
  <div class="alert alert-warning">
    <p>Student sucessfully created <em>Thank you.</em></p>
  </div>
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}">

{% endblock %}

colleage/templates/students/students_by_department.html
{% extends 'dashboard.html' %}

{% block dashboard-body %}

<div class="row">
    <div class="col-9">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Registration</th>
                    <th scope="col">Name</th>
                    <th scope="col">Department</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'students:student_details' pk=student.id %}">
                            {{ student.roll }}
                    </th>
                    <td>
                        <a href="{% url 'students:student_details' pk=student.id %}">
                            {{ student.registration_number }}</td>
                    <td>
                        <a href="{% url 'students:student_details' pk=student.id %}">
                            <img src="{{ student.photo.url }}" class="mr-2 rounded-circle" height=24 width=24>
                            {{ student.name }}
                    </td>
                    <td>
                        <a href="{% url 'students:student_details' pk=student.id %}">
                            {{ student.department.name }}
                    </td>
                    <td>
                        <a href="{% url 'students:student_details' pk=student.id %}">
                            {{ student.semester }}
                    </td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-success">
                                <i class="fas fa-cogs"></i>
                            </button>
                            <a href="{% url 'students:update_student' pk=student.id %}" class="btn btn-secondary">
                                <i class="fas fa-edit"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-3">
        {% include "students/student_list_sidebar.html" %}
    </div>
</div>

{% endblock %}

colleage/templates/students/students_list.html
{% extends 'dashboard.html' %}
{% load permission_tags %}
{% block dashboard-body %}

<div class="row">
  <div class="col-12">
    {% if user|has_role:'admin'%}
      <a href="{% url 'students:export_users_details_csv' %}">
      <button type="button" class="btn btn-outline-info float-right">
        Export all Students</button></a>
    {% endif %}
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Registration</th>
          <th scope="col">Name</th>
          <th scope="col">Mobile</th>
          <th scope="col">Email</th>
          <th scope="col">Total Fee</th>
          <th scope="col">Paid</th>
          <th scope="col">Due</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr class="student">
          <th scope="row">
            <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.id }}
          </th>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.registration_number }}</td>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
            <img src="{{ student.photo.url }}" class="mr-2 rounded-circle" height=24 width=24>
            {{ student.user.username }}
          </td>
          <td>
              <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.mobile }}
          </td>
           <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.user.email }}
          </td>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
              {% if user|has_role:'admin'%}
                {{ student.total_amount }}
              {% elif user.get_username == student.user.username%}
                {{ student.total_amount }}
              {%else%}
                Not Visible
              {% endif %}
          </td>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
               {% if user|has_role:'admin'%}
                {{ student.paid_amount }}
              {% elif user.get_username == student.user.username%}
                {{ student.paid_amount }}
              {%else%}
                Not Visible
              {% endif %}
          </td>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
               {% if user|has_role:'admin'%}
                {{ student.due_amount }}
              {% elif user.get_username == student.user.username%}
                {{ student.due_amount }}
              {%else%}
                Not Visible
              {% endif %}
          </td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn btn-success">
                <a href="{% url 'students:student_details' pk=student.id %}"><p style="color:black">View</p></a>
              </button>
            </div>
            {% if user|has_role:'admin'%}
               <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-info">
                  <a href="{% url 'students:update_student' pk=student.id %}"><p style="color:black">Edit</p></a>
                </button>
              </div>

               <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-danger">
                  <a href="{% url 'students:delete_student' pk=student.pk %}"<p style="color:black">Delete</p></a>
                </button>
              </div>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>

</div>

  <script>
      var rows = document.getElementsByTagName("tr")
      var i = 1
      {% if user|has_role:'admin'%}

          {% for student in students %}
            {% if student.due_amount != 0%}
              rows[i++].style.backgroundColor = "rgba(255, 99, 71, 0.4)";
            {% else %}
              rows[i++].style.backgroundColor = "white";
            {% endif %}
          {% endfor %}
      {%else%}
          {% for student in students %}
            {% if user.get_username == student.user.username %}
              rows[i].style.backgroundColor = "rgba(255, 99, 71, 0.4)";
            {% endif %}
             i = i + 1;
          {% endfor %}
     {% endif %}


</script>
{% endblock %}

colleage/templates/students/update_student.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="update-student">
  <div id="update-student-inner">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8 py-5">
          <div id="student-update-form">
            <form class="sudent-update-form" action="." method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <a href="{% url 'index_view' %}" class="btn btn-dark">
                <i class="fas fa-arrow-left"></i> Back
              </a>
              <input class="btn btn-info" type="submit" value="Update Details">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}